<main id="main" class="main">

    <div class="pagetitle">
        <h1 style=" font-family: 'Poppins' ">Les health</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= BASE_URL ?>" index>Home</a></li>
                <li class="breadcrumb-item active">Confirmación</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">
            <div class="card">
                <div class="card-header">
                    <center>
                        <h4 class="card-header">Registro y Listado de citas por confirmar <img class="img-fluid"
                                style="width:3%" src="<?= PLANTILLA ?>assets/img/isotipo.svg" alt="">
                            <span class="d-none d-lg-block"
                                style="color: black; font-family: 'Poppins', sans-serif; font-weight: 900;">LES
                                health</span>
                        </h4>
                    </center>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end pt-3">
                        <!-- Button trigger modal -->
                        <button style="background-color: #48276f; border-color: #48276f;" type="button" class="btn btn-primary" data-bs-toggle="modal"
                            data-bs-target="#modalAgregarDoctor">
                            <i class="fa-solid fa-plus"></i> Agregar Nuevo
                        </button>
                    </div>


                </div>
                <div class="card-body mt-5">

                    <table id="table" class="display">
                        <thead>
                            <th>ID Cita</th>
                            <th>Hora solicitada</th>
                            <th>Fecha Solicitada</th>
                            <th>Nombre Paciente</th>
                            <th>Motivo</th>
                            <th>Prioridad</th>
                            <th>Evidencia</th>

                            <th>Acción</th>
                        </thead>
                        <tbody>
                            <?= $this->tabla ?>
                        </tbody>

                    </table>

                </div>
            </div>
        </div>

    </section>




    <!-- Modal  para agregar Doctor-->
    <div class="modal fade" id="modalAgregarDoctor" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false"
        aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#48276f">
                    <h1 style="color: #ffffffff; font-family: 'Poppins', sans-serif; font-weight: 500;"
                        class="modal-title fs-5" id="exampleModalLabel"> Agregar Nuevo Doctor <i
                            class="fa-solid fa-stethoscope"></i></h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <form class="row" method="post" id="formAgregarDoctor" enctype="multipart/form-data">

                            <div class="mb-3 col-lg-12">
                                <label for="" class="form-label">Nombre Completo</label>
                                <input type="text" class="form-control" id="nombre" name="nombre" required
                                    autocomplete="off">
                            </div>

                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Sexo</label>
                                <select class="form-select" name="sexo" id="sexo">
                                    <option value="Limpieza">Seleccione una Opción</option>
                                    <option value="Masculino">Masculino</option>
                                    <option value="Femenino">Femenino</option>
                                </select>
                            </div>


                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Especialidad</label>
                                <input type="text" class="form-control" id="especialidad" name="especialidad" required>
                            </div>

                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Numero de telefono</label>
                                <input type="tel" class="form-control" id="numero" name="numero" required
                                    autocomplete="off">
                            </div>



                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Correo Electronico</label>
                                <input type="email" class="form-control" id="correo" name="correo" required
                                    autocomplete="off">
                            </div>

                             <div class="mb-3 col-lg-12">
                                <label for="" class="form-label">Nombre Usuario</label>
                                <input type="text" class="form-control" id="nombreU" name="nombreU" required  autocomplete="off">
                                <span id="result"></span>
                            </div>

                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Contraseña Usuario</label>
                                <div class="input-group">
                                    <input type="password" class="form-control" id="clave" name="clave" required>
                                    <span id="ocultar" class="input-group-text"><i onclick="ocultarPass('clave',this);"
                                            class="fa-solid fa-eye"></i></span>
                                </div>
                            </div>

                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Repita Contraseña </label>
                                <div class="input-group">



                                    <input type="password" class="form-control" id="repetir" name="repetir" required>

                                    <span class="input-group-text"><i onclick="ocultarPass('repetir',this);"
                                            class="fa-solid fa-eye"></i></span>
                                </div>


                            </div>

                           



                            <div class="mb-3 col-lg-12">
                                <label for="" class="form-label">Foto del Doctor</label>
                                <input type="file" class="form-control" id="imagen" name="imagen" required
                                    accept="image/jpg, image/png, image/jpeg">
                            </div>

                            <div id="previewContainer" class="mt-3 text-center">
                                <img id="previewImage" src="#" alt="Previsualización"
                                    style="max-width: 150px; display: none;" />
                            </div>

                            


                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal"><i class="fa-solid fa-ban"></i>
                        Cancelar</button>
                    <button type="submit" class="btn btn-primary"><i class="fa-solid fa-plus"></i> Agregar
                        Registro</button>
                </div>

                </form>
            </div>
        </div>
    </div>

       <!-- Modal  para Editar Doctor-->

        <div class="modal fade" id="modalEditarDoctor" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false"
        aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#48276f">
                    <h1 style="color: #ffffffff; font-family: 'Poppins', sans-serif; font-weight: 500;"
                        class="modal-title fs-5" id="exampleModalLabel"> Editar Datos Del Doctor <i
                            class="fa-solid fa-stethoscope"></i></h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <form class="row" method="post" id="formEditarDoctor" enctype="multipart/form-data" autocomplete="off">

                            <div class="mb-3 col-lg-12">
                                <label for="" class="form-label">ID Doctor</label>
                                <input type="text" class="form-control" id="idUp" name="idUp" >
                            </div>


                            <div class="mb-3 col-lg-12">
                                <label for="" class="form-label">Nombre Completo</label>
                                <input type="text" class="form-control" id="nombreUp" name="nombreUp" 
                                    autocomplete="off">
                            </div>

                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Sexo</label>
                                <select class="form-select" name="sexoUp" id="sexoUp">
                                    <option value="Limpieza">Seleccione una Opción</option>
                                    <option value="Masculino">Masculino</option>
                                    <option value="Femenino">Femenino</option>
                                </select>
                            </div>


                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Especialidad</label>
                                <input type="text" class="form-control" id="especialidadUp" name="especialidadUp" >
                            </div>

                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Numero de telefono</label>
                                <input type="tel" class="form-control" id="numeroUp" name="numeroUp" 
                                    autocomplete="off">
                            </div>



                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Correo Electronico</label>
                                <input type="tel" class="form-control" id="correoUp" name="correoUp" 
                                    autocomplete="off">
                            </div>

                             <div class="mb-3 col-lg-12">
                                <label for="" class="form-label">Nombre Usuario</label>
                                <input type="text" class="form-control" id="nombreUsUp" name="nombreUsUp"  autocomplete="off">
                                <span id="result"></span>
                            </div>

                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Contraseña Usuario</label>
                                <div class="input-group">
                                    <input type="password" class="form-control" id="claveUp" name="claveUsUp" autocomplete="new-password">
                                    <span id="ocultar" class="input-group-text"><i onclick="ocultarPass('claveUp',this);"
                                            class="fa-solid fa-eye"></i></span>
                                </div>
                            </div>

                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Repita Contraseña </label>
                                <div class="input-group">



                                    <input type="password" class="form-control" id="repetirUp" name="repetirUp" autocomplete="off">

                                    <span class="input-group-text"><i onclick="ocultarPass('repetirUp',this);"
                                            class="fa-solid fa-eye"></i></span>
                                </div>


                            </div>

                           



                            <div class="mb-3 col-lg-12">
                                <label for="" class="form-label">Foto del Doctor</label>
                                <input type="file" class="form-control" id="imagenUp" name="imagenUp" 
                                    accept="image/jpg, image/png, image/jpeg">
                            </div>

                            <div id="mb-3 col-lg-12" class="mt-3">
                                <label for="" class="form-label">Imagen Actual del Doctor</label>
                                <img id="previewImageUp" src="#" alt="Previsualización"
                                    style="max-width: 150px; display:block" />
                            </div>

                            


                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal"><i class="fa-solid fa-ban"></i>
                        Cancelar</button>
                    <button type="submit" class="btn btn-primary"><i class="fa-solid fa-plus"></i> Agregar
                        Registro</button>
                </div>

                </form>
            </div>
        </div>
    </div>






</main>