<main id="main" class="main">

    <div class="pagetitle">
        <h1>HappyMemories</h1>
        <nav>
            <ol class="breadcrumb">
<li class="breadcrumb-item"><a href="<?= BASE_URL ?>"index>Home</a></li>                <li class="breadcrumb-item active">Cementerio</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">
            <div class="card">
                <div class="card-header">
                    <center>
                        <h4 class="card-header">Registro y Listado de Cementerio</h4>
                    </center>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end pt-3">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                            data-bs-target="#modalAgregarUsuario">
                            <i class="fa-solid fa-plus"></i> Agregar Nuevo
                        </button>
                    </div>


                </div>
                <div class="card-body mt-5">

                    <table id="table" class="display">
                        <style>
  .password-cell {
    max-width: 150px;       
    white-space: nowrap;    
    overflow: hidden;       
    text-overflow: ellipsis;
  }
</style>
                        <thead>
                            <th>ID usuario</th>
                            <th>Nombre usuario</th>
                            <th>Password</th>
                            <th>Rol</th>
                            <th>Acción</th>
                        </thead>
                        <tbody>
                            <?= $this->tabla ?>
                        </tbody>

                    </table>

                </div>
            </div>
        </div>

    </section>




    <!-- Modal -->
    <div class="modal fade" id="modalAgregarUsuario" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#ecc006">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <form class="row" method="post" id="formAgregarUsuario" enctype="multipart/form-data">

                            <div class="mb-3 col-lg-12">
                                <label for="" class="form-label">Nombre Usuario</label>
                                <input type="text" class="form-control" id="nombre" name="nombre" required>
                                <span id="result"></span>
                            </div>

                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Contraseña Usuario</label>
                                <div class="input-group">
                                    <input type="password" class="form-control" id="clave" name="clave" required>
                                    <span id="ocultar" class="input-group-text"><i onclick="ocultarPass('clave',this);"
                                            class="fa-solid fa-eye"></i></span>
                                </div>
                            </div>

                            <div class="mb-3 col-lg-6">
                                <label for="" class="form-label">Repita Contraseña </label>
                                <div class="input-group">



                                    <input type="password" class="form-control" id="repetir" name="repetir" required>

                                    <span class="input-group-text"><i onclick="ocultarPass('repetir',this);"
                                            class="fa-solid fa-eye"></i></span>
                                </div>


                            </div>

                            <div class="mb-3 col-lg-12">
                                <label for="" class="form-label">Rol Usuario</label>
                                <select name="rol" class="form-select">
                                    <option value="0">Seleccione Rol De Usuario</option>
                                    <option value="administrador">Administrador</option>
                                    <option value="funcionario">Funcionario</option>
                                    <option value="familiar">Familiar</option>

                                </select>
                            </div>





                    </div>






                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal"><i class="fa-solid fa-ban"></i> Cancelar</button>
                    <button atyle="color:#fff" type="submit" class="btn btn-primary"><i class="fa-solid fa-plus"></i> Agregar Usuario</button>
                </div>

                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalEditarUsuario" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="modalEditarLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header" style="background-color:#ecc006">
                <h1 class="modal-title fs-5" id="modalEditarLabel">Editar Usuario</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form class="row" method="post" id="formEditarUsuario" enctype="multipart/form-data">
                    <input type="hidden" id="id_usuario" name="id_usuario">

                    <div class="mb-3 col-lg-12">
                        <label for="nombreEditar" class="form-label">Nombre Usuario</label>
                        <input type="text" class="form-control" id="nombreEditar" name="nombre" required>
                        <span id="resultEditar"></span>
                    </div>

                    <div class="mb-3 col-lg-6">
                        <label for="claveEditar" class="form-label">Contraseña Usuario</label>
                        <div class="input-group">
                            <input type="password" class="form-control" id="claveEditar" name="clave" required>
                            <span id="ocultarEditar" class="input-group-text">
                                <i onclick="ocultarPass('claveEditar',this);" class="fa-solid fa-eye"></i>
                            </span>
                        </div>
                    </div>

                    <div class="mb-3 col-lg-6">
                        <label for="repetirEditar" class="form-label">Repita Contraseña</label>
                        <div class="input-group">
                            <input type="password" class="form-control" id="repetirEditar" name="repetir" required>
                            <span class="input-group-text">
                                <i onclick="ocultarPass('repetirEditar',this);" class="fa-solid fa-eye"></i>
                            </span>
                        </div>
                    </div>

                    <div class="mb-3 col-lg-12">
                        <label for="rolEditar" class="form-label">Rol Usuario</label>
                        <select name="rol" id="rolEditar" class="form-select" required>
                            <option value="0">Seleccione Rol De Usuario</option>
                            <option value="administrador">Administrador</option>
                            <option value="funcionario">Funcionario</option>
                            <option value="familiar">Familiar</option>
                        </select>
                    </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">
                    <i class="fa-solid fa-ban"></i> Cancelar
                </button>
                <button type="submit" class="btn btn-primary">
                    <i class="fa-solid fa-edit"></i> Guardar Cambios
                </button>
            </div>
                </form>
        </div>
    </div>
</div>


</main>